# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HACKLIFE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HACKLIFE
  pod 'CodableFirebase'
   pod 'SDWebImageSwiftUI'
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'lottie-ios'
pod 'Firebase/InAppMessaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Auth'
pod 'FirebaseFirestoreSwift'
pod 'SDWebImage', '~> 5.0'
pod 'IHKeyboardAvoiding'

end
